DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS PASSENGER;
DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS TRAIN;
DROP TABLE IF EXISTS STATION;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE STATION
(
  ID   BIGINT       NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TRAIN
(
  ID    BIGINT NOT NULL AUTO_INCREMENT,
  SEATS INT    NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SCHEDULE
(
  ID             BIGINT    NOT NULL AUTO_INCREMENT,
  TRAIN_ID       BIGINT    NOT NULL,
  STATION_ID     BIGINT    NOT NULL,
  DEPARTURE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN (ID),
  FOREIGN KEY (STATION_ID) REFERENCES STATION (ID)
);

CREATE TABLE PASSENGER
(
  ID         BIGINT       NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME  VARCHAR(255) NOT NULL,
  BIRTHDAY   DATE         NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TICKET
(
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  PASSENGER_ID BIGINT NOT NULL,
  TRAIN_ID     BIGINT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ID),
  FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN (ID)
);

CREATE TABLE EMPLOYEE
(
  ID       BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN    VARCHAR(255),
  PASSWORD VARCHAR(255),
  PRIMARY KEY (ID)
);